### ISSUE TITLE
Problem with T411.php

### ISSUE THREAD

**Issue by nadrelaxe** [Guisch/autoDLT411#1]
When I try to display test.php and/or searchTU.php I always have the same error

`Notice:` Trying to get property of non-object in /var/www/autodl/src/T411.php on line 80
`Notice:` Trying to get property of non-object in /var/www/autodl/src/T411.php on line 81

Also, you should update the URL from t411.li to t411.ai.

**Comment by Guisch** [comment]
You're right for the URL but the error is due to the fact that the API is
not broken at this time (have a look at this forum post to follow the api
status: https://forum.t411.ai/discussion/45826/bugs-informations-demandes/p2
)

2017-04-09 13:33 GMT+02:00 nadrelaxe <notifications@github.com>:

**Comment by nadrelaxe** [comment]
Ok well! So let's just wait for the API to be back! :3 

I'd love to help you on that project.

Au passage je suis français donc pas besoin de faire de manières!
